spring:
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
    datasource:
        url: jdbc:mysql://localhost:3306/lazyload?serverTimezone=UTC
        username: root
        password: root