// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfR8w9o7rWaCpcd_0H7GsR7DiKXdLmMa4',
    appId: '1:222362602289:web:a0158a458b434dc0d57e10',
    messagingSenderId: '222362602289',
    projectId: 'flutter-firebase-auth-15b22',
    authDomain: 'flutter-firebase-auth-15b22.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth-15b22.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs8irZv9PJNcgACQyCUW3FVonzyoMz7b8',
    appId: '1:222362602289:android:676117a26655ed11d57e10',
    messagingSenderId: '222362602289',
    projectId: 'flutter-firebase-auth-15b22',
    storageBucket: 'flutter-firebase-auth-15b22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNtij_sQU_g32_0tZJljqe5Wr-YzyVId8',
    appId: '1:222362602289:ios:711024f7fa356c8ed57e10',
    messagingSenderId: '222362602289',
    projectId: 'flutter-firebase-auth-15b22',
    storageBucket: 'flutter-firebase-auth-15b22.firebasestorage.app',
    iosClientId: '222362602289-7aftqoad5qt3kdabohh4e111r10m54op.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

}