ktor:
    application:
        modules:
            - com.yiyongc.sbpktor.ApplicationKt.module
    deployment:
        port: 8080
postgres:
  url: "jdbc:postgresql://localhost:5432/sbpktor"
  user: dbuser
  password: dbuser@123